name: PMD Static Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pmd-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: PMD analysis
        id: pmd
        uses: pmd/pmd-github-action@v2
        with:
          version: '7.15.0'
          rulesets: 'rulesets/java/quickstart.xml'
          analyzeModifiedFilesOnly: true
          createGitHubAnnotations: true
          uploadSarifReport: true

      - name: Fail build on new violations
        # Only exit(1) if there *are* violations AND *no* “skip pmd” tag
        if: >
          steps.pmd.outputs.violations != '0' &&
          !(
            github.event_name == 'push' &&
            contains(toLower(github.event.head_commit.message), 'skip pmd')
            ||
            github.event_name == 'pull_request' &&
            contains(toLower(github.event.pull_request.title), 'skip pmd')
          )
        run: exit 1
